In [93]:
import pandas as pd, numpy as np

import matplotlib.pyplot as plt

In [94]:
dt = pd.read_csv('Downloads\spam.csv')

In [95]:
dt.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [96]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5574 entries, 0 to 5573
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5574 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [97]:
dt.describe()

Category                 Message
count      5574                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4827                      30

In [74]:
dt.isnull().sum()

Category    0
Message     2
dtype: int64

In [75]:
dt.dropna(axis = 0, how = 'any', inplace=True)

In [76]:
dt['Spam'] = dt.Category.apply(lambda x : 1 if x == 'spam' else 0)

dt.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [77]:
dt

Category                                            Message  Spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5569     spam  This is the 2nd time we have tried 2 contact u...     1
5570      ham               Will ü b going to esplanade fr home?     0
5571      ham  Pity, * was in mood for that. So...any other s...     0
5572      ham  The guy did some bitching but I acted like i'd...     0
5573      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [78]:
dt.Category.shape, dt.Message.shape , dt.Spam.shape

((5572,), (5572,), (5572,))

In [79]:
dt = dt.drop('Category',1)

### HAM = 0  SPAM = 1

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train,  y_test = train_test_split(dt.Message ,dt.Spam , train_size=0.8, random_state=42)

In [81]:
X_train.shape , y_train.shape, X_test.shape, y_test.shape

((4457,), (4457,), (1115,), (1115,))

In [82]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_count = v.fit_transform(X_train.values)

X_train_count.toarray()[:3]


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [83]:
X_train_count.shape, y_train.shape

((4457, 7701), (4457,))

In [84]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_count, y_train)



MultinomialNB()

In [85]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'free free adidas 50',
    'Hey Lets catch up'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1, 1, 0], dtype=int64)

In [86]:
X_test_count = v.transform(X_test)

model.score(X_test_count, y_test)

0.9919282511210762

SKLEARN PIPELINE

In [87]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
  
     ('v' , CountVectorizer()),
    ('nb', MultinomialNB())
])

In [88]:
clf.fit(X_train, y_train)

Pipeline(steps=[('v', CountVectorizer()), ('nb', MultinomialNB())])

In [89]:
clf.score(X_test,y_test)

0.9919282511210762

In [90]:
clf.predict(emails)

array([0, 1, 1, 0], dtype=int64)